name: build-notconf-base

on: [push, pull_request]

env:
  IMAGE_PATH: ghcr.io/mzagozen/notconf/
  CONTAINER_RUNTIME: podman

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Cache deps
      uses: actions/cache@v3
      with:
        path: src
        key: src-${{ hashFiles('Makefile') }}

    - name: Update deps
      run: make clone-deps

    - name: Build container images
      run: make build

    - name: Run tests
      run: |
        make test
        make test-podman-to-docker

    - name: Log in to the container registry
      uses: redhat-actions/podman-login@v1
      if: ${{ github.ref_name == 'main' }}
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Tag and push container images
      if: ${{ github.ref_name == 'main' }}
      run: |
        make tag-release
        make push-release

    - name: Store container logs in artifact
      uses: actions/upload-artifact@v3
      with:
        name: container-logs
        path: container-logs/
