name: build-notconf-base

on: [push, pull_request]

env:
  IMAGE_PATH: ghcr.io/mzagozen/notconf/

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Cache deps
      uses: actions/cache@v2
      with:
        path: src
        key: src-${{ hashFiles('Makefile') }}

    - name: Update deps
      run: make clone-deps

    - name: Build docker images
      run: make build

    - name: Run tests
      run: make test

    - name: Log in to the Container registry
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      if: ${{ github.ref_name == 'main' }}
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Tag and push docker images
      if: ${{ github.ref_name == 'main' }}
      run: |
        make tag-release
        make push-release

    - name: Store container logs in artifact
      uses: actions/upload-artifact@v2
      with:
        name: docker-logs
        path: docker-logs/

