name: build-notconf-base

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      CI_COMMIT_REF_NAME: ${{ github.ref_name }}

    steps:
    - uses: actions/checkout@v2

    - name: Cache deps
      uses: actions/cache@v2
      with:
        path: src
        key: src-${{ hashFiles('Makefile') }}

    - name: Update deps
      run: make clone-deps

    - name: Set up docker buildx
      uses: docker/setup-buildx-action@v1

    - name: Build (and cache) the build-tools-source docker target
      uses: docker/build-push-action@v2
      with:
        context: .
        push: false
        load: true
        target: build-tools-source
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Build docker images
      run: make build

    - name: Install test prerequisites
      run: pip3 install netconf-console2

    - name: Run tests
      run: make test
