name: build-notconf-base

on: [push, pull_request]

env:
  IMAGE_PATH: ghcr.io/mzagozen/notconf/
  CONTAINER_RUNTIME: podman

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Show podman info
      run: |
        podman info --format '{{ .Host.LogDriver }}'
        podman create --help | grep log-driver
        podman info

    - uses: actions/checkout@v3

    - name: Cache deps
      uses: actions/cache@v3
      with:
        path: src
        key: src-${{ hashFiles('Makefile') }}

    - name: Update deps
      run: make clone-deps

    - name: Build container images
      run: make build

    - name: Install test prerequisites
      run: |
        pip3 install pyang
        sudo apt-get install -qy xmlstarlet

    - name: Run tests
      run: |
        make test
        make test-podman-to-docker

    - name: Save logs for running containers
      if: always()
      # After a successful test run there should be no containers left in the
      # GitHub runner (a runner is an isolated VM). Any leftover containers are
      # a result of a test failing so we should get the logs!
      run: CNT_PREFIX= make save-logs

    - name: Log in to the container registry
      uses: redhat-actions/podman-login@v1
      if: ${{ github.ref_name == 'main' }}
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Tag and push container images
      if: ${{ github.ref_name == 'main' }}
      run: |
        make tag-release
        make push-release

    - name: Store container logs in artifact
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: container-logs
        path: container-logs/
